"""Tests for the readme CLI command and generate_readme service method."""

import tempfile
from pathlib import Path

import pytest
from typer.testing import CliRunner

from pyrite.cli import app
from pyrite.config import KBConfig, KBType, PyriteConfig, Settings
from pyrite.models.factory import build_entry
from pyrite.schema import generate_entry_id
from pyrite.services.kb_service import KBService
from pyrite.storage.database import PyriteDB
from pyrite.storage.index import IndexManager
from pyrite.storage.repository import KBRepository

runner = CliRunner()


@pytest.fixture
def readme_env():
    """Environment for readme tests."""
    with tempfile.TemporaryDirectory() as tmpdir:
        tmpdir = Path(tmpdir)
        db_path = tmpdir / "index.db"

        kb_path = tmpdir / "test-kb"
        kb_path.mkdir()

        kb_config = KBConfig(
            name="test-kb",
            path=kb_path,
            kb_type=KBType.GENERIC,
            description="A test knowledge base",
        )

        config = PyriteConfig(
            knowledge_bases=[kb_config],
            settings=Settings(index_path=db_path),
        )

        # Create some entries
        repo = KBRepository(kb_config)
        for i in range(3):
            title = f"Test Note {i}"
            entry = build_entry(
                "note",
                entry_id=generate_entry_id(title),
                title=title,
                body=f"Body for note {i}.",
                importance=5 + i,
                tags=["test"],
            )
            repo.save(entry)

        db = PyriteDB(db_path)
        IndexManager(db, config).index_all()

        yield {"config": config, "db": db, "tmpdir": tmpdir, "kb_path": kb_path}

        db.close()


def _patch_config(env):
    import contextlib
    from unittest.mock import patch

    @contextlib.contextmanager
    def _multi_patch():
        with patch("pyrite.cli.load_config", return_value=env["config"]):
            with patch("pyrite.cli.context.load_config", return_value=env["config"]):
                yield

    return _multi_patch()


class TestGenerateReadme:
    def test_readme_content(self, readme_env):
        svc = KBService(readme_env["config"], readme_env["db"])
        readme = svc.generate_readme("test-kb")

        assert "# test-kb" in readme
        assert "A test knowledge base" in readme
        assert "## Contents" in readme
        assert "## Entries" in readme
        assert "Test Note" in readme
        assert "Generated by Pyrite" in readme

    def test_readme_type_counts(self, readme_env):
        svc = KBService(readme_env["config"], readme_env["db"])
        readme = svc.generate_readme("test-kb")

        assert "| note |" in readme or "| Note |" in readme.lower()

    def test_readme_empty_kb(self, readme_env):
        with tempfile.TemporaryDirectory() as tmpdir2:
            tmpdir2 = Path(tmpdir2)
            empty_path = tmpdir2 / "empty-kb"
            empty_path.mkdir()

            empty_kb = KBConfig(
                name="empty-kb",
                path=empty_path,
                kb_type=KBType.GENERIC,
            )
            config = PyriteConfig(
                knowledge_bases=[empty_kb],
                settings=readme_env["config"].settings,
            )
            svc = KBService(config, readme_env["db"])
            readme = svc.generate_readme("empty-kb")

            assert "# empty-kb" in readme
            assert "Generated by Pyrite" in readme

    def test_readme_kb_not_found(self, readme_env):
        svc = KBService(readme_env["config"], readme_env["db"])
        with pytest.raises(Exception, match="not found"):
            svc.generate_readme("nonexistent-kb")


@pytest.mark.cli
class TestReadmeCommand:
    def test_readme_stdout(self, readme_env):
        with _patch_config(readme_env):
            result = runner.invoke(app, ["readme", "--kb", "test-kb"])
            assert result.exit_code == 0
            assert "# test-kb" in result.output

    def test_readme_write_flag(self, readme_env):
        with _patch_config(readme_env):
            result = runner.invoke(app, ["readme", "--kb", "test-kb", "--write"])
            assert result.exit_code == 0
            readme_path = readme_env["kb_path"] / "README.md"
            assert readme_path.exists()
            content = readme_path.read_text()
            assert "# test-kb" in content

    def test_readme_output_file(self, readme_env):
        output_path = readme_env["tmpdir"] / "custom-readme.md"
        with _patch_config(readme_env):
            result = runner.invoke(
                app, ["readme", "--kb", "test-kb", "--output", str(output_path)]
            )
            assert result.exit_code == 0
            assert output_path.exists()
            content = output_path.read_text()
            assert "# test-kb" in content
